export const IDENT_A: Record<string, string> = {
  nom: 'Nom',
  prenom: 'Prenom',
  dateNaissance: 'Date de naissance',
  age: 'Age',
  lieuExamen: "Lieu de l'examen",
  dateExamen: "Date de l'examen",
  dureeExamen: "Duree de l'examen",
};

export const IDENT_B: Record<string, string> = {
  expertisePenale: 'Expertise penale',
  identiteMagistratDemandeur: 'Identite du magistrat demandeur',
  expertiseCivile: 'Expertise civile',
  examenSurRequisition: 'Examen sur requisition',
  identiteOPJ: "Identite de l'OPJ",
  examenSurCommissionRogatoire: 'Examen sur commission rogatoire',
};

export const IDENT_C: Record<string, string> = {
  misEnCause: 'Mis en cause',
  victime: 'Victime',
  temoin: 'Temoin',
};

export const IDENT_D: Record<string, string> = {
  rappelDesFaits: 'Rappel des faits',
};

export const IDENT_E: Record<string, string> = {
  pvAudition: "PV d'audition",
  dossierMedical: 'Dossier medical',
  certificatsMedicaux: 'Certificats medicaux',
  rapportsExpertiseAnterieurs: "Rapports d'expertise anterieurs",
  autresPreciser: 'Autres documents',
};

export const ANAM_A: Record<string, string> = {
  pathologieCardiovasculaire: 'Pathologie cardiovasculaire',
  pathologieNeurologique: 'Pathologie neurologique',
  pathologieEndocrinienne: 'Pathologie endocrinienne',
  pathologieInfectieuseChronique: 'Pathologie infectieuse chronique',
  cancer: 'Cancer',
  traumatismeCranien: 'Traumatisme cranien',
  autresMedicauxPreciser: 'Autres antecedents medicaux',
  deficitVisuel: 'Deficit visuel',
  deficitAuditif: 'Deficit auditif',
  aucunTraitementMedicamenteux: 'Aucun traitement medicamenteux',
  traitementMedicamenteuxPreciser: 'Traitement medicamenteux',
};

export const ANAM_B: Record<string, string> = {
  jamaisHospitalise: 'Jamais hospitalise',
  hospitalisationLibre: 'Hospitalisation libre',
  hospitalisationSousContrainte: 'Hospitalisation sous contrainte',
  hospitalisationEnCours: 'Hospitalisation en cours',
  nombreHospitalisations: "Nombre d'hospitalisations",
  datesHospitalisations: "Dates d'hospitalisations",
  suiviPsychiatriqueEnCours: 'Suivi psychiatrique en cours',
  suiviPsychologiqueEnCours: 'Suivi psychologique en cours',
  suiviAnterieur: 'Suivi anterieur',
  jamaisSuivi: 'Jamais suivi',
  antidepresseur: 'Antidepresseur',
  anxiolytique: 'Anxiolytique',
  hypnotique: 'Hypnotique',
  neuroleptique: 'Neuroleptique',
  thymoregulateur: 'Thymoregulateur',
  antiAndrogene: 'Anti-androgene',
  observanceTraitement: 'Observance du traitement',
  autresTraitementsPreciser: 'Autres traitements',
  tentativeSuicide: 'Tentative de suicide',
  nombreTS: 'Nombre de tentatives',
  datesTS: 'Dates des tentatives',
  moyensUtilises: 'Moyens utilises',
  scarifications: 'Scarifications',
  automutilations: 'Automutilations',
  ruptureSoinsAvantFaits: 'Rupture de soins / arret du traitement avant les faits',
};

export const ANAM_C: Record<string, string> = {
  alcoolNonConsommateur: 'Non consommateur alcool',
  alcoolConsommationOccasionnelle: 'Consommation occasionnelle alcool',
  alcoolConsommationReguliere: 'Consommation reguliere alcool',
  alcoolConsommationQuotidienne: 'Consommation quotidienne alcool',
  alcoolQuantiteEstimeeJour: 'Quantite estimee/jour',
  alcooloDependance: 'Alcoolo-dependance',
  antecedentsSevrage: 'Antecedents de sevrage',
  antecedentsDeliriumTremens: 'Antecedents de delirium tremens',
  alcoolAntecedents: 'Antecedents de consommation d\'alcool (actuellement sevre/abstinent)',
  alcoolAntecedentsDuree: 'Duree de la consommation passee d\'alcool',
  alcoolAntecedentsType: 'Type de consommation d\'alcool passee',
  cannabis: 'Cannabis',
  cannabisFrequence: 'Frequence cannabis',
  cannabisAntecedents: 'Antecedents de consommation de cannabis (actuellement abstinent)',
  cannabisAntecedentsDuree: 'Duree de la consommation passee de cannabis',
  cannabisAntecedentsType: 'Type de consommation de cannabis passee',
  cocaine: 'Cocaine',
  cocaineFrequence: 'Frequence cocaine',
  cocaineAntecedents: 'Antecedents de consommation de cocaine (actuellement abstinent)',
  cocaineAntecedentsDuree: 'Duree de la consommation passee de cocaine',
  cocaineAntecedentsType: 'Type de consommation de cocaine passee',
  heroine: 'Heroine',
  heroineFrequence: 'Frequence heroine',
  heroineAntecedents: 'Antecedents de consommation d\'heroine (actuellement abstinent)',
  heroineAntecedentsDuree: 'Duree de la consommation passee d\'heroine',
  heroineAntecedentsType: 'Type de consommation d\'heroine passee',
  amphetamines: 'Amphetamines',
  amphetaminesFrequence: 'Frequence amphetamines',
  amphetaminesAntecedents: 'Antecedents de consommation d\'amphetamines (actuellement abstinent)',
  amphetaminesAntecedentsDuree: 'Duree de la consommation passee d\'amphetamines',
  amphetaminesAntecedentsType: 'Type de consommation d\'amphetamines passee',
  mdmaEcstasy: 'MDMA / Ecstasy',
  mdmaEcstasyFrequence: 'Frequence MDMA',
  mdmaEcstasyAntecedents: 'Antecedents de consommation de MDMA/Ecstasy (actuellement abstinent)',
  mdmaEcstasyAntecedentsDuree: 'Duree de la consommation passee de MDMA/Ecstasy',
  mdmaEcstasyAntecedentsType: 'Type de consommation de MDMA/Ecstasy passee',
  autresDrogues: 'Autres drogues',
  autresDroguesPreciser: 'Autres drogues (preciser)',
  autresDroguesAntecedents: 'Antecedents de consommation d\'autres drogues (actuellement abstinent)',
  autresDroguesAntecedentsDuree: 'Duree de la consommation passee d\'autres drogues',
  autresDroguesAntecedentsType: 'Type de consommation d\'autres drogues passee',
  methadone: 'Methadone',
  buprenorphine: 'Buprenorphine',
  observanceSubstitution: 'Observance substitution',
  nonFumeur: 'Non fumeur',
  fumeur: 'Fumeur',
  fumeurQuantiteJour: 'Quantite cigarettes/jour',
  fumeurAntecedents: 'Antecedents de tabagisme (actuellement sevre/non-fumeur)',
  fumeurAntecedentsDuree: 'Duree du tabagisme passe',
  fumeurAntecedentsType: 'Type de consommation de tabac passee',
  jeuPathologique: 'Jeu pathologique (jeux d\'argent, casino, paris sportifs)',
  achatsCompulsifs: 'Achats compulsifs',
  addictionEcransJeuxVideo: 'Addiction aux ecrans / jeux video',
};

export const ANAM_D: Record<string, string> = {
  aucunAntecedentJudiciaire: 'Aucun antecedent judiciaire',
  condamnationsAnterieures: 'Condamnations anterieures',
  condamnationsNature: 'Nature des condamnations',
  incarcerationAnterieure: 'Incarceration anterieure',
  incarcerationNombre: "Nombre d'incarcerations",
  incarcerationDuree: "Duree d'incarceration",
  agePremierContactJustice: 'Age premier contact justice',
  antecedentsInfractionsSexuelles: 'Antecedents infractions sexuelles',
  infractionsSexuellesNature: 'Nature infractions sexuelles',
  inscriptionFIJAIS: 'Inscription FIJAIS',
  proceduresEnCours: 'Procedures en cours',
  proceduresEnCoursNature: 'Nature procedures en cours',
};

export const ANAM_E: Record<string, string> = {
  mereEnVie: 'Mere en vie',
  pereEnVie: 'Pere en vie',
  vieCommune: 'Vie commune des parents',
  fratrie: 'Fratrie',
  fratrieNombre: 'Nombre dans la fratrie',
  rangFratrie: 'Rang dans la fratrie',
  pathologiePsychiatriquesFamille: 'Pathologies psychiatriques familiales',
  suicidesFamille: 'Suicides familiaux',
  alcoolismeFamilial: 'Alcoolisme familial',
  violencesPhysiques: 'Violences physiques',
  violencesPsychologiques: 'Violences psychologiques',
  violencesSexuelles: 'Violences sexuelles',
  negligence: 'Negligence',
  carenceAffectiveMajeure: 'Carence affective majeure',
  carenceEducativePrecoce: 'Carence educative precoce',
  placementEnfance: "Placement dans l'enfance",
  placementDuree: 'Duree du placement',
};

export const ANAM_F: Record<string, string> = {
  scolariteNormale: 'Scolarite normale',
  redoublements: 'Redoublements',
  redoublementsNombre: 'Nombre de redoublements',
  orientationSpecialisee: 'Orientation specialisee',
  diplomeObtenu: 'Diplome obtenu',
  troublesDys: 'Troubles dys',
  difficultesApprentissages: "Difficultes d'apprentissage",
  troublesComportementEcole: "Troubles du comportement a l'ecole",
  descolarisation: 'Descolarisation',
  victimeHarcelementScolaire: 'Victime de harcelement scolaire',
};

export const ANAM_G: Record<string, string> = {
  enActivite: 'En activite',
  auChomage: 'Au chomage',
  enArretMaladie: 'En arret maladie',
  invalidite: 'Invalidite',
  retraite: 'Retraite',
  profession: 'Profession',
  stabiliteProfessionnelle: 'Stabilite professionnelle',
  'changementsFréquentsEmploi': "Changements frequents d'emploi",
  conflitsProfessionnels: 'Conflits professionnels',
};

export const ANAM_H: Record<string, string> = {
  celibataire: 'Celibataire',
  enCouple: 'En couple',
  marie: 'Marie(e)',
  divorce: 'Divorce(e)',
  separe: 'Separe(e)',
  veuf: 'Veuf/Veuve',
  enfants: 'Enfants',
  enfantsNombre: "Nombre d'enfants",
  contactRegulierEnfants: 'Contact regulier avec les enfants',
  mesuresJudiciairesEnfants: 'Mesures judiciaires enfants',
  domicileStable: 'Domicile stable',
  sansDomicileFixe: 'Sans domicile fixe',
  heberge: 'Heberge',
  enInstitution: 'En institution',
  isolementSocial: 'Isolement social',
  relationsAmicales: 'Relations amicales',
  relationsFamilialesPreservees: 'Relations familiales preservees',
  tutelle: 'Tutelle',
  curatelle: 'Curatelle',
  curatelleSimple: 'Curatelle simple',
  curatelleRenforcee: 'Curatelle renforcee',
  sauvegardeDejustice: 'Sauvegarde de justice',
  habilitationFamiliale: 'Habilitation familiale',
  mandatProtectionFuture: 'Mandat de protection future',
  mesureProtection: 'Mesure de protection',
  dateMiseEnPlace: 'Date de mise en place',
  membreFamille: 'Membre de la famille (tuteur/curateur)',
  mandataireJudiciaire: 'Mandataire judiciaire',
  preciserTuteurCurateur: 'Tuteur/curateur (preciser)',
  dateRenouvellementPrevue: 'Date de renouvellement prevue',
};

export const ANAM_I: Record<string, string> = {
  educationSexuelleRecue: 'Education sexuelle recue',
  agePremieresRelationsSexuelles: 'Age premieres relations sexuelles',
  relationsSexuellesConsenties: 'Relations sexuelles consenties',
  heterosexuelle: 'Heterosexuelle',
  homosexuelle: 'Homosexuelle',
  bisexuelle: 'Bisexuelle',
  autresOrientations: 'Autres orientations',
  activiteSexuelle: 'Activite sexuelle',
  satisfactionSexuelle: 'Satisfaction sexuelle',
  troublesSexuels: 'Troubles sexuels',
  troublesSexuelsPreciser: 'Troubles sexuels (preciser)',
  victimisationEnfance: "Victimisation dans l'enfance",
  victimisationAdulte: "Victimisation a l'age adulte",
  victimisationPreciser: 'Victimisation (preciser)',
};

export const EXAM_A: Record<string, string> = {
  cooperant: 'Cooperant',
  reticent: 'Reticent',
  mutique: 'Mutique',
  hostile: 'Hostile',
  mefiant: 'Mefiant',
  tenueVestimentaireAdaptee: 'Tenue vestimentaire adaptee',
  hygieneCorrecte: 'Hygiene correcte',
  negligence: 'Negligence',
  contactConserve: 'Contact conserve',
  contactFroid: 'Contact froid',
  contactFuyant: 'Contact fuyant',
  contactAdhesif: 'Contact adhesif',
};

export const EXAM_B: Record<string, string> = {
  vigilanceNormale: 'Vigilance normale',
  obnubilation: 'Obnubilation',
  somnolence: 'Somnolence',
  stupeur: 'Stupeur',
  orienteTemps: 'Oriente dans le temps',
  orienteEspace: "Oriente dans l'espace",
  orientePersonne: 'Oriente sur la personne',
  attentionPreservee: 'Attention preservee',
  distractibilite: 'Distractibilite',
  fatigabiliteAttentionnelle: 'Fatigabilite attentionnelle',
  memoireImmediatePreservee: 'Memoire immediate preservee',
  memoireRecentePreservee: 'Memoire recente preservee',
  memoireAnciennePreservee: 'Memoire ancienne preservee',
  amnesieFaits: 'Amnesie des faits',
  faussesReconnaissances: 'Fausses reconnaissances',
  fabulations: 'Fabulations',
  niveauIntellectuelEstime: 'Niveau intellectuel estime',
  retardMentalSuspecte: 'Retard mental suspecte',
  aptitudesInsight: "Aptitudes a l'insight",
  critiqueConservee: 'Critique conservee',
  anosognosie: 'Anosognosie',
};

export const EXAM_C: Record<string, string> = {
  reconnaissanceEmotionsFaciales: 'Reconnaissance emotions faciales',
  comprehensionEtatMentalAutrui: "Comprehension de l'etat mental d'autrui",
  difficultesPdvAutrui: "Difficultes a prendre le point de vue d'autrui",
  difficultesSousEntendus: 'Difficultes avec les sous-entendus',
  interpretationsLitterales: 'Interpretations litterales',
  comprehensionReglesImplicites: 'Comprehension des regles implicites',
  difficultesBehaviorContextSocial: "Difficultes d'adaptation au contexte social",
  interpretationsPersecut: 'Interpretations persecutoires',
  naivete: 'Naivete',
  empathieCognitive: 'Empathie cognitive',
  empathieEmotionnelle: 'Empathie emotionnelle',
  comportementAdapte: 'Comportement adapte',
  inhibitionMarquee: 'Inhibition marquee',
  intrusivite: 'Intrusivite',
  difficulteDistanceInterpersonnelle: 'Difficulte de distance interpersonnelle',
  retentissementVieFamiliale: 'Retentissement vie familiale',
  retentissementVieProfessionnelle: 'Retentissement vie professionnelle',
  retentissementRelationsAffectives: 'Retentissement relations affectives',
};

export const EXAM_D: Record<string, string> = {
  'discoursCohérent': 'Discours coherent',
  discoursLogique: 'Discours logique',
  proposAdaptes: 'Propos adaptes',
  mythomanie: 'Mythomanie',
  mensongesUtilitaires: 'Mensonges utilitaires',
  debitNormal: 'Debit normal',
  debitRalenti: 'Debit ralenti',
  debitAccelere: 'Debit accelere',
  logorrhee: 'Logorrhee',
  barrages: 'Barrages',
  fading: 'Fading',
  coqALane: 'Coq-a-l\'ane',
  incoherence: 'Incoherence',
  schizophasie: 'Schizophasie',
  perseverations: 'Perseverations',
  tangentialite: 'Tangentialite',
  prolixite: 'Prolixite',
  neologismesPresents: 'Neologismes',
};

export const EXAM_E: Record<string, string> = {
  presenceSyndrome: 'Syndrome depressif present',
  tristesseHumeur: "Tristesse de l'humeur",
  anhedonie: 'Anhedonie',
  perteInteret: "Perte d'interet",
  emoussementAffectif: 'Emoussement affectif',
  douleurMoralePresente: 'Douleur morale presente',
  douleurMoraleIntense: 'Douleur morale intense',
  culpabilite: 'Culpabilite',
  sentimentIndignite: "Sentiment d'indignite",
  devalorisation: 'Devalorisation',
  sentimentIncapacite: "Sentiment d'incapacite",
  autoAccusations: 'Auto-accusations',
  pessimisme: 'Pessimisme',
  desespoir: 'Desespoir',
  ideesMort: 'Idees de mort',
  ideesSuicidaires: 'Idees suicidaires',
  scenarioSuicidaire: 'Scenario suicidaire',
  intentionSuicidaire: 'Intention suicidaire',
  'risqueSuicidaireImmédiat': 'Risque suicidaire immediat',
  troublesSommeil: 'Troubles du sommeil',
  insomniesEndormissement: "Insomnies d'endormissement",
  insomnieMilieuNuit: 'Insomnie milieu de nuit',
  reveilPrecoce: 'Reveil precoce',
  hypersomnie: 'Hypersomnie',
  troublesAppetit: "Troubles de l'appetit",
  anorexie: 'Anorexie',
  hyperphagie: 'Hyperphagie',
  variationPonderale: 'Variation ponderale',
  asthenie: 'Asthenie',
  perteEnergie: "Perte d'energie",
  troublesLibido: 'Troubles de la libido',
  bradypsychie: 'Bradypsychie',
  bradykinesie: 'Bradykinesie',
  hypomimie: 'Hypomimie',
  clinophilie: 'Clinophilie',
  aggravationMatinale: 'Aggravation matinale',
};

export const EXAM_F: Record<string, string> = {
  presenceSyndrome: 'Syndrome maniaque present',
  exaltationHumeur: "Exaltation de l'humeur",
  euphorie: 'Euphorie',
  irritabilite: 'Irritabilite',
  labilitieEmotionnelle: 'Labilite emotionnelle',
  agitationPsychomotrice: 'Agitation psychomotrice',
  hyperactivite: 'Hyperactivite',
  desinhibition: 'Desinhibition',
  familiariteExcessive: 'Familiarite excessive',
  tachypsychie: 'Tachypsychie',
  fuiteIdees: 'Fuite des idees',
  logorrhee: 'Logorrhee',
  coqALane: 'Coq-a-l\'ane',
  megalomanie: 'Megalomanie',
  projetsIrrealistes: 'Projets irrealistes',
  suresTimationSoi: 'Surestime de soi',
  conduitesARisque: 'Conduites a risque',
  achatsInconsideres: 'Achats inconsideres',
  desinhibitionSexuelle: 'Desinhibition sexuelle',
  ideesDelirantes: 'Idees delirantes',
  hallucinations: 'Hallucinations',
};

export const EXAM_G: Record<string, string> = {
  presenceSyndrome: 'Syndrome anxieux present',
  inquietudeExcessive: 'Inquietude excessive',
  ruminationsAnxieuses: 'Ruminations anxieuses',
  peurSansObjet: 'Peur sans objet',
  anticipationAnxieuse: 'Anticipation anxieuse',
  sentimentDangerImminent: 'Sentiment de danger imminent',
  palpitations: 'Palpitations',
  sueurs: 'Sueurs',
  tremblements: 'Tremblements',
  oppressionThoracique: 'Oppression thoracique',
  dyspnee: 'Dyspnee',
  nausees: 'Nausees',
  paresthesies: 'Paresthesies',
  vertiges: 'Vertiges',
  antecedentAttaquesPanique: "Antecedents d'attaques de panique",
  attaquesPaniqueRecurrentes: 'Attaques de panique recurrentes',
  peurMourir: 'Peur de mourir',
  peurDevenirFou: 'Peur de devenir fou',
  agoraphobie: 'Agoraphobie',
  phobieSociale: 'Phobie sociale',
  phobiesSpecifiques: 'Phobies specifiques',
  conduitesEvitement: "Conduites d'evitement",
  retentissementFonctionnel: 'Retentissement fonctionnel',
};

export const EXAM_H: Record<string, string> = {
  presenceSyndrome: 'Syndrome obsessionnel-compulsif present',
  penseesObsedantes: 'Pensees obsedantes',
  ideesIntrusives: 'Idees intrusives',
  caractereEgoDystonique: 'Caractere ego-dystonique',
  lutteAnxieuse: 'Lutte anxieuse',
  rituelsCompulsifs: 'Rituels compulsifs',
  verifications: 'Verifications',
  lavage: 'Lavage',
  rangement: 'Rangement',
  comptage: 'Comptage',
  souffrancePsychique: 'Souffrance psychique',
  retentissementFonctionnel: 'Retentissement fonctionnel',
};

export const EXAM_I: Record<string, string> = {
  presenceSyndrome: 'Syndrome de stress post-traumatique present',
  souvenirsintrusive: 'Souvenirs intrusifs',
  cauchemars: 'Cauchemars',
  flashbacks: 'Flashbacks',
  detresseRappelTraumatisme: 'Detresse au rappel du traumatisme',
  evitementPenseesTraumatisme: 'Evitement des pensees liees au traumatisme',
  evitementLieuxPersonnes: 'Evitement des lieux/personnes',
  amnesieCertainsAspects: 'Amnesie de certains aspects',
  croyancesNegativesSoi: 'Croyances negatives sur soi',
  culpabilitePersistante: 'Culpabilite persistante',
  emoussementAffectif: 'Emoussement affectif',
  detachement: 'Detachement',
  hypervigilance: 'Hypervigilance',
  sursautsExageres: 'Sursauts exageres',
  irritabilite: 'Irritabilite',
  troublesDuSommeil: 'Troubles du sommeil',
};

export const EXAM_J: Record<string, string> = {
  presenceSyndrome: 'Syndrome delirant present',
  presenceIdeesDelirantes: 'Presence idees delirantes',
  adhesionTotale: 'Adhesion totale',
  adhesionPartielle: 'Adhesion partielle',
  persecution: 'Persecution',
  prejudice: 'Prejudice',
  reference: 'Reference',
  influence: 'Influence',
  megalomanie: 'Megalomanie',
  mystique: 'Mystique',
  erotomaniaque: 'Erotomaniaque',
  jalousie: 'Jalousie',
  hypocondriaque: 'Hypocondriaque',
  ruine: 'Ruine',
  culpabilite: 'Culpabilite',
  nihilismeCotard: 'Nihilisme (Cotard)',
  mecanismeInterpretatifs: 'Mecanismes interpretatifs',
  mecanismeImaginatifs: 'Mecanismes imaginatifs',
  mecanismeHallucinatoires: 'Mecanismes hallucinatoires',
  mecanismeIntuitifs: 'Mecanismes intuitifs',
  systematise: 'Systematise',
  nonSystematise: 'Non systematise',
  hermetique: 'Hermetique',
  enSecteur: 'En secteur',
  envahissant: 'Envahissant',
  angoisse: 'Angoisse',
  perplexite: 'Perplexite',
  passageActeHeteroAgressif: 'Passage a l\'acte hetero-agressif',
  passageActeAutoAgressif: 'Passage a l\'acte auto-agressif',
};

export const EXAM_K: Record<string, string> = {
  presenceSyndrome: 'Syndrome hallucinatoire present',
  hallucinationsAcousticoVerbales: 'Hallucinations acoustico-verbales',
  voixCommentantActes: 'Voix commentant les actes',
  voixDialoguantEntreElles: 'Voix dialoguant entre elles',
  voixImperatives: 'Voix imperatives',
  hallucinationsVisuelles: 'Hallucinations visuelles',
  hallucinationsOlfactives: 'Hallucinations olfactives',
  hallucinationsCenesthesiques: 'Hallucinations cenesthesiques',
  illusions: 'Illusions',
};

export const EXAM_L: Record<string, string> = {
  presenceSyndrome: 'Syndrome dissociatif present',
  discordanceIdeoAffective: 'Discordance ideo-affective',
  reactionsEmotionnellesInadaptees: 'Reactions emotionnelles inadaptees',
  riresImmotives: 'Rires immotives',
  barrages: 'Barrages',
  fading: 'Fading',
  diffluence: 'Diffluence',
  bizarreriesComportementales: 'Bizarreries comportementales',
  manieres: 'Manieres',
  paramimies: 'Paramimies',
  ambivalence: 'Ambivalence',
};

export const EXAM_M: Record<string, string> = {
  presenceSyndrome: 'Syndrome catatonique present',
  catalepsie: 'Catalepsie',
  flexibiliteCireuse: 'Flexibilite cireuse',
  negativisme: 'Negativisme',
  stereotypiesMotrices: 'Stereotypies motrices',
  stereotypiesVerbales: 'Stereotypies verbales',
  echolalieEchopraxie: 'Echolalie / Echopraxie',
  stupeurCatatonique: 'Stupeur catatonique',
  agitationCatatonique: 'Agitation catatonique',
};

export const EXAM_N: Record<string, string> = {
  presenceSyndrome: 'Symptomes negatifs presents',
  emoussementAffectif: 'Emoussement affectif',
  aboulie: 'Aboulie',
  apragmatisme: 'Apragmatisme',
  retraitSocial: 'Retrait social',
  alogie: 'Alogie',
  anhedonie: 'Anhedonie',
};

export const EXAM_O: Record<string, string> = {
  presenceSyndrome: 'Syndrome confusionnel present',
  obnubilation: 'Obnubilation',
  fluctuations: 'Fluctuations',
  desorientationTemporoSpatiale: 'Desorientation temporo-spatiale',
  amnesieAnterograde: 'Amnesie anterograde',
  perplexiteAnxieuse: 'Perplexite anxieuse',
  onirisme: 'Onirisme',
  debutAigu: 'Debut aigu',
};

export const EXAM_O_BIS: Record<string, string> = {
  troubleUsageSubstancesPresent: 'Troubles lies aux substances presents a l\'examen',
  symptomesEbriete: 'Symptomes d\'intoxication / d\'ebriete',
  symptomesSevrage: 'Symptomes de sevrage (manque)',
  modifPsychoComportementales: 'Modifications psycho-comportementales (desinhibition, labilite...)',
  foetorAlcoolique: 'Foetor alcoolique (haleine)',
  dysarthrie: 'Dysarthrie / Elocution pateuse',
  ataxieEquilibre: 'Troubles de l\'equilibre / Ataxie motrice',
  tremblementsSubstances: 'Tremblements',
  sueursSubstances: 'Sueurs / Signes vegetatifs',
  signesDenutrition: 'Signes physiques de denutrition / hepatomegalie',
};

export const EXAM_P: Record<string, string> = {
  presenceSyndrome: 'Syndrome dementiel present',
  oublisAMesure: 'Oublis a mesure',
  amnesieRetrograde: 'Amnesie retrograde',
  troublesFonctionsExecutives: 'Troubles des fonctions executives',
  troublesGnosiques: 'Troubles gnosiques',
  troublesPraxiques: 'Troubles praxiques',
  aphasie: 'Aphasie',
  manqueDuMot: 'Manque du mot',
  perteAutonomie: "Perte d'autonomie",
  evolutionProgressive: 'Evolution progressive',
};

export const EXAM_Q: Record<string, string> = {
  presenceSyndrome: 'Troubles des conduites alimentaires presents',
  restrictionAlimentaire: 'Restriction alimentaire',
  peurDeGrossir: 'Peur de grossir',
  distorsionImageCorporelle: "Distorsion de l'image corporelle",
  amenorrhee: 'Amenorrhee',
  accesBoulimiques: 'Acces boulimiques',
  conduitesCompensatoires: 'Conduites compensatoires',
  hyperphagieBoulimique: 'Hyperphagie boulimique',
};

export const EXAM_R: Record<string, string> = {
  presenceSyndrome: 'TDAH present',
  diagnosticPose: 'Diagnostic pose',
  depuis: 'Depuis',
  parMedecinGeneraliste: 'Par medecin generaliste',
  parPsychiatre: 'Par psychiatre',
  parPedopsychiatre: 'Par pedopsychiatre',
  parNeurologue: 'Par neurologue',
  difficulteMaintenirAttention: "Difficulte a maintenir l'attention",
  distractibiliteImportante: 'Distractibilite importante',
  oublisFrequents: 'Oublis frequents',
  difficulteOrganiserTaches: 'Difficulte a organiser les taches',
  evitementTachesEffortMental: "Evitement des taches a effort mental",
  perteFrequenteObjets: "Perte frequente d'objets",
  difficulteSuivreInstructions: 'Difficulte a suivre les instructions',
  agitationMotrice: 'Agitation motrice',
  difficulteResterAssis: 'Difficulte a rester assis',
  sentimentAgitationInterieure: "Sentiment d'agitation interieure",
  difficulteSeDetendre: 'Difficulte a se detendre',
  loquaciteExcessive: 'Loquacite excessive',
  interruptionDesAutres: 'Interruption des autres',
  impulsiviteDecisions: 'Impulsivite dans les decisions',
  difficulteAttendreSonTour: 'Difficulte a attendre son tour',
  retentissementProfessionnel: 'Retentissement professionnel',
  retentissementSocial: 'Retentissement social',
  retentissementFamilial: 'Retentissement familial',
  retentissementJudiciaire: 'Retentissement judiciaire',
  traitementMedicamenteux: 'Traitement medicamenteux',
  traitementPreciser: 'Traitement (preciser)',
  observance: 'Observance',
  suiviPsychologique: 'Suivi psychologique',
  amenagementsProfessionnelsScolaires: 'Amenagements professionnels/scolaires',
};

export const EXAM_S: Record<string, string> = {
  presenceSyndrome: 'Trouble paraphilique present',
  rapportesParSujet: 'Rapportes par le sujet',
  reconnus: 'Reconnus',
  nies: 'Nies',
  pedophilieAttraction: 'Pedophilie - Attraction',
  pedophilieAgeVictimes: 'Age des victimes',
  pedophilieSexeVictimes: 'Sexe des victimes',
  pedophiliePassagesActe: 'Passages a l\'acte',
  pedophilieExclusif: 'Type exclusif',
  pedophilieNonExclusif: 'Type non exclusif',
  hebephilieAttraction: 'Hebephilie - Attraction',
  exhibitionnismeExposition: 'Exhibitionnisme',
  exhibitionnismeFrequence: 'Frequence exhibitionnisme',
  exhibitionnismeContexte: 'Contexte exhibitionnisme',
  voyeurismeObservation: 'Voyeurisme',
  voyeurismeFrequence: 'Frequence voyeurisme',
  frotteurismeContact: 'Frotteurisme',
  sadismeExcitation: 'Sadisme - Excitation',
  sadismeFantasmes: 'Sadisme - Fantasmes',
  sadismePassagesActe: 'Sadisme - Passages a l\'acte',
  masochismeExcitation: 'Masochisme',
  fetichismeObjets: 'Fetichisme',
  fetichismeTypeObjet: 'Type objet fetichisme',
  transvestismeExcitation: 'Transvestisme',
  zoophilieActivite: 'Zoophilie',
  necrophilieAttraction: 'Necrophilie',
  autresParaphiliesPreciser: 'Autres paraphilies',
  fantasmesPresentDepuis: 'Fantasmes presents depuis',
  fantasmesFrequence: 'Frequence fantasmes',
  fantasmesDetresse: 'Detresse liee aux fantasmes',
  fantasmesTentativesControle: 'Tentatives de controle',
  fantasmesEfficacite: 'Efficacite du controle',
  passageActeAntecedents: 'Antecedents de passage a l\'acte',
  passageActeNombreEstime: 'Nombre estime',
  passageActeAgePremier: 'Age au premier passage a l\'acte',
  passageActeEvolution: 'Evolution',
  passageActeContexte: 'Contexte',
  pornoReguliere: 'Consommation pornographie reguliere',
  pornoFrequence: 'Frequence pornographie',
  pornoLegaleStandard: 'Pornographie legale standard',
  pornoImpliquantMineurs: 'Pornographie impliquant des mineurs',
  pornoViolente: 'Pornographie violente',
  pornoAutre: 'Autre pornographie',
  pornoEscalade: 'Escalade pornographique',
  connaissanceCaractereIllegal: 'Connaissance du caractere illegal',
  comprehensionPrejudiceVictimes: 'Comprehension du prejudice aux victimes',
  minimisationInterdit: "Minimisation de l'interdit",
  deniInterdit: "Deni de l'interdit",
  controleCapacite: 'Capacite de controle',
  controleFacteursDeclenchants: 'Facteurs declenchants',
  controleStrategiesEvitement: "Strategies d'evitement",
  rationalisations: 'Rationalisations',
  minimisationDistorsion: 'Minimisation / Distorsion',
  attributionResponsabiliteVictime: 'Attribution responsabilite a la victime',
  deniGravite: 'Deni de gravite',
  empathiePresente: 'Empathie presente',
  empathiePartielle: 'Empathie partielle',
  empathieAbsence: "Absence d'empathie",
  demandeSpontanee: 'Demande spontanee de soins',
  acceptationPriseEnCharge: 'Acceptation prise en charge',
  refusSoins: 'Refus de soins',
  ambivalence: 'Ambivalence',
  suiviSexologique: 'Suivi sexologique',
  tcc: 'TCC',
  traitementAntiAndrogene: 'Traitement anti-androgene',
  antecedentsObservance: 'Observance anterieure',
  antecedentsEfficacite: 'Efficacite anterieure',
};

export const EXAM_T: Record<string, string> = {
  presenceSyndrome: 'Trouble de la personnalite present',
  troubleSelectionne: 'Type de trouble',
  elementsCliniquesComplementaires: 'Elements cliniques complementaires',
};

export const EXAM_U: Record<string, string> = {
  presenceSyndrome: 'Syndrome impulsif / agressivite present',
  passagesActeImpulsifs: 'Passages a l\'acte impulsifs',
  difficulteControlerColere: 'Difficulte a controler la colere',
  intoleranceFrustration: 'Intolerance a la frustration',
  antecedentsViolence: 'Antecedents de violence',
  violenceVerbale: 'Violence verbale',
  violencePhysique: 'Violence physique',
  violenceInstrumentale: 'Violence instrumentale',
  violenceReactionnelle: 'Violence reactionnelle',
  dangerositePourAutrui: 'Dangerosite pour autrui',
  dangerositePourSoi: 'Dangerosite pour soi',
};

export const EXAM_X: Record<string, string> = {
  presenceSyndrome: 'Troubles a symptomatologie somatique presents',
  troubleSymptomatologieSomatique: 'Trouble a symptomatologie somatique (plaintes physiques excessives)',
  crainteExcessiveMaladie: 'Crainte excessive d\'avoir une maladie (Hypocondrie)',
  troubleConversion: 'Trouble de conversion / trouble neurologique fonctionnel',
  troubleFacticePathomimie: 'Trouble factice / Pathomimie classique',
  syndromeMunchhausen: 'Syndrome de Munchhausen',
  syndromeMunchhausenProcuration: 'Syndrome de Munchhausen par procuration',
  facteursPsychologiquesAggravants: 'Facteurs psychologiques aggravant une affection medicale',
};

export const EXAM_V: Record<string, string> = {
  suspicionSimulation: 'Suspicion de simulation (Malingering)',
  exagerationSymptomes: 'Exageration des symptomes',
  productionSymptomesAbsurdes: 'Production de symptomes absurdes (Ganser)',
  reticenceOppositionCalculee: 'Reticence / Opposition calculee',
  incoherenceObservationPlaintes: 'Incoherence observation clinique / plaintes',
};

export const EXAM_W: Record<string, string> = {
  presenceSyndrome: 'TSA present',
  diagnosticOuSuspicionTSA: 'Diagnostic etabli ou suspicion clinique de TSA',
  troublesInteractionsSociales: 'Troubles des interactions sociales reciproques',
  interetsRestreintsStereotypies: 'Interets restreints / Stereotypies',
  particularitesSensorielles: 'Particularites sensorielles',
};

export const FAITS_COMPREHENSION: Record<string, string> = {
  comprendNatureFaits: 'Comprend la nature des faits',
  comprendPorteeActes: 'Comprend la portee des actes',
  comprendCaractereIllegal: 'Comprend le caractere illegal',
  rappelFaits: 'Rappel des faits',
};

export const FAITS_RECONNAISSANCE: Record<string, string> = {
  reconnaissanceTotale: 'Reconnaissance totale',
  reconnaissancePartielle: 'Reconnaissance partielle',
  minimisation: 'Minimisation',
  deniTotal: 'Deni total',
  negationQualification: 'Negation de la qualification',
};

export const FAITS_ETAT_MENTAL: Record<string, string> = {
  pathologiePsychiatriqueActive: 'Pathologie psychiatrique active',
  symptomesPsychotiques: 'Symptomes psychotiques',
  intoxicationAlcoolique: 'Intoxication alcoolique',
  intoxicationStupefiants: 'Intoxication stupefiants',
  etatConfusionnel: 'Etat confusionnel',
  etatEmotionnelParticulier: 'Etat emotionnel particulier',
};

export const FAITS_CONSCIENCE: Record<string, string> = {
  conscienceClaire: 'Conscience claire',
  alterationConscience: 'Alteration de la conscience',
};

export const FAITS_AMNESIE: Record<string, string> = {
  totale: 'Amnesie totale',
  partielle: 'Amnesie partielle',
  absente: 'Amnesie absente',
  lacunaire: 'Amnesie lacunaire',
  alleguee: 'Amnesie alleguee',
};

export const FAITS_PREMEDITATION: Record<string, string> = {
  signesPremeditation: 'Signes de premeditation',
  acteImpulsif: 'Acte impulsif',
};

export const REL_EXPLICATIONS: Record<string, string> = {
  pathologiePsychiatrique: 'Pathologie psychiatrique',
  troubleHumeur: "Trouble de l'humeur",
  delire: 'Delire',
  hallucinations: 'Hallucinations',
  intoxication: 'Intoxication',
  troublePersonnalite: 'Trouble de la personnalite',
  troubleParaphilique: 'Trouble paraphilique',
  deficienceIntellectuelle: 'Deficience intellectuelle',
  aucunePathologieMentale: 'Aucune pathologie mentale',
};

export const REL_CAUSALITE: Record<string, string> = {
  lienDirect: 'Lien direct',
  lienEssentiel: 'Lien essentiel',
  lienIndirect: 'Lien indirect',
  facteurContributif: 'Facteur contributif',
  absenceDeLien: 'Absence de lien',
  faitsPossiblesSansTroubles: 'Faits possibles sans troubles',
};

export const DIAG_PRINCIPAL: Record<string, string> = {
  absencePathologie: 'Absence de pathologie',
  troubleDepressif: 'Trouble depressif',
  troubleDepressifPrecision: 'Precision trouble depressif',
  troubleBipolaire: 'Trouble bipolaire',
  schizophrenie: 'Schizophrenie',
  troubleDelirant: 'Trouble delirant',
  troubleSchizoAffectif: 'Trouble schizo-affectif',
  troubleAdaptation: "Trouble de l'adaptation",
  etatStressPostTraumatique: 'Etat de stress post-traumatique',
  troubleAnxieuxGeneralise: 'Trouble anxieux generalise',
  troublePanique: 'Trouble panique',
  toc: 'TOC',
  troubleUsageAlcool: "Trouble de l'usage d'alcool",
  troubleUsageSubstances: "Trouble de l'usage de substances",
  troublePersonnalite: 'Trouble de la personnalite',
  troublePersonnaliteType: 'Type trouble personnalite',
  troubleParaphilique: 'Trouble paraphilique',
  troubleParaphiliqueType: 'Type trouble paraphilique',
  retardMental: 'Retard mental',
  retardMentalDegre: 'Degre retard mental',
  syndromeDementiel: 'Syndrome dementiel',
  autre: 'Autre diagnostic',
  autrePrecision: 'Precision autre diagnostic',
};

export const DANG_PSYCHIATRIQUE: Record<string, string> = {
  autrui: 'Dangerosite pour autrui',
  soiMeme: 'Dangerosite pour soi-meme',
  sexuelle: 'Dangerosite sexuelle',
};

export const DANG_RECIDIVE: Record<string, string> = {
  eleve: 'Risque eleve',
  moyen: 'Risque moyen',
  faible: 'Risque faible',
};

export const DANG_FACTEURS_RISQUE: Record<string, string> = {
  absenceCritique: 'Absence de critique',
  minimisationFaits: 'Minimisation des faits',
  troublePersonnalite: 'Trouble de la personnalite',
  troubleParaphilique: 'Trouble paraphilique',
  addiction: 'Addiction',
  isolementSocial: 'Isolement social',
  absenceSuivi: 'Absence de suivi',
};

export const DANG_FACTEURS_PROTECTION: Record<string, string> = {
  conscienceTrouble: 'Conscience du trouble',
  demandeSoins: 'Demande de soins',
  soutienFamilial: 'Soutien familial',
  insertionSocioPro: 'Insertion socio-professionnelle',
};

export const DANG_NECESSITE_SOINS: Record<string, string> = {
  urgence: 'Urgence',
  courtTerme: 'Court terme',
  ambulatoire: 'Ambulatoire',
  hospitalisation: 'Hospitalisation',
  injonctionSoins: 'Injonction de soins',
  aucunSoin: 'Aucun soin necessaire',
};

export const DANG_INJONCTION: Record<string, string> = {
  suiviPsychiatrique: 'Suivi psychiatrique',
  suiviPsychologique: 'Suivi psychologique',
  suiviSexologique: 'Suivi sexologique',
  traitementMedicamenteux: 'Traitement medicamenteux',
  traitementAntiAndrogene: 'Traitement anti-androgene',
  addictologie: 'Addictologie',
  tcc: 'TCC',
  therapieGroupe: 'Therapie de groupe',
  autreTherapie: 'Autre therapie',
};

export const DANG_MODALITES: Record<string, string> = {
  frequence: 'Frequence',
  duree: 'Duree',
  structure: 'Structure',
  medecinCoordonnateur: 'Medecin coordonnateur',
};

export const DANG_PRONOSTIC: Record<string, string> = {
  favorableSousTraitement: 'Favorable sous traitement',
  reserve: 'Reserve',
  defavorable: 'Defavorable',
};
